package com.nbport.eportws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-06T17:10:07.675+08:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://eportws.nbport.com/", name = "EportWebServiceDelegate")
@XmlSeeAlso({ObjectFactory.class})
public interface EportWebServiceDelegate {

    @WebMethod
    @RequestWrapper(localName = "callService", targetNamespace = "http://eportws.nbport.com/", className = "com.nbport.eportws.CallService")
    @ResponseWrapper(localName = "callServiceResponse", targetNamespace = "http://eportws.nbport.com/", className = "com.nbport.eportws.CallServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String callService(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebMethod
    @RequestWrapper(localName = "callServiceEx", targetNamespace = "http://eportws.nbport.com/", className = "com.nbport.eportws.CallServiceEx")
    @ResponseWrapper(localName = "callServiceExResponse", targetNamespace = "http://eportws.nbport.com/", className = "com.nbport.eportws.CallServiceExResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String callServiceEx(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5
    );

    @WebMethod(operationName = "MDMSubscribe")
    @RequestWrapper(localName = "MDMSubscribe", targetNamespace = "http://eportws.nbport.com/", className = "com.nbport.eportws.MDMSubscribe")
    @ResponseWrapper(localName = "MDMSubscribeResponse", targetNamespace = "http://eportws.nbport.com/", className = "com.nbport.eportws.MDMSubscribeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String mdmSubscribe(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
