
package service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EportWebServiceDelegate", targetNamespace = "http://eportws.nbport.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EportWebServiceDelegate {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "callService", targetNamespace = "http://eportws.nbport.com/", className = "service.CallService")
    @ResponseWrapper(localName = "callServiceResponse", targetNamespace = "http://eportws.nbport.com/", className = "service.CallServiceResponse")
    public String callService(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "callServiceEx", targetNamespace = "http://eportws.nbport.com/", className = "service.CallServiceEx")
    @ResponseWrapper(localName = "callServiceExResponse", targetNamespace = "http://eportws.nbport.com/", className = "service.CallServiceExResponse")
    public String callServiceEx(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MDMSubscribe")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "MDMSubscribe", targetNamespace = "http://eportws.nbport.com/", className = "service.MDMSubscribe")
    @ResponseWrapper(localName = "MDMSubscribeResponse", targetNamespace = "http://eportws.nbport.com/", className = "service.MDMSubscribeResponse")
    public String mdmSubscribe(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
