
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EportWebServiceService", targetNamespace = "http://eportws.nbport.com/", wsdlLocation = "http://www.yibutong.com.cn/eport-dataservices/EportWebServicePort?wsdl")
public class EportWebServiceService
    extends Service
{

    private final static URL EPORTWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException EPORTWEBSERVICESERVICE_EXCEPTION;
    private final static QName EPORTWEBSERVICESERVICE_QNAME = new QName("http://eportws.nbport.com/", "EportWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.yibutong.com.cn/eport-dataservices/EportWebServicePort?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EPORTWEBSERVICESERVICE_WSDL_LOCATION = url;
        EPORTWEBSERVICESERVICE_EXCEPTION = e;
    }

    public EportWebServiceService() {
        super(__getWsdlLocation(), EPORTWEBSERVICESERVICE_QNAME);
    }

    public EportWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EPORTWEBSERVICESERVICE_QNAME, features);
    }

    public EportWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, EPORTWEBSERVICESERVICE_QNAME);
    }

    public EportWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EPORTWEBSERVICESERVICE_QNAME, features);
    }

    public EportWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EportWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EportWebServiceDelegate
     */
    @WebEndpoint(name = "EportWebServicePort")
    public EportWebServiceDelegate getEportWebServicePort() {
        return super.getPort(new QName("http://eportws.nbport.com/", "EportWebServicePort"), EportWebServiceDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EportWebServiceDelegate
     */
    @WebEndpoint(name = "EportWebServicePort")
    public EportWebServiceDelegate getEportWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://eportws.nbport.com/", "EportWebServicePort"), EportWebServiceDelegate.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EPORTWEBSERVICESERVICE_EXCEPTION!= null) {
            throw EPORTWEBSERVICESERVICE_EXCEPTION;
        }
        return EPORTWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
