
package com.nbport.eportws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-06T17:10:07.628+08:00
 * Generated source version: 3.1.10
 * 
 */
public final class EportWebServiceDelegate_EportWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://eportws.nbport.com/", "EportWebServiceService");

    private EportWebServiceDelegate_EportWebServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = EportWebServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        EportWebServiceService ss = new EportWebServiceService(wsdlURL, SERVICE_NAME);
        EportWebServiceDelegate port = ss.getEportWebServicePort();  
        
        {
        System.out.println("Invoking callService...");
        String usr = "WS_WJDS";
		String pwd  = "64a7909b3b3abf538f7fe1f746aa155660d6bfa457b53da44495609845642823";//SHA-256
		String serviceID = "QueryLogisticsStatus";
        String applyData = "{direction:'E',bl_no:'COSU6126486030',status:['00']}";
        // java.lang.String _callService_arg0 = "";
        // java.lang.String _callService_arg1 = "";
        // java.lang.String _callService_arg2 = "";
        // java.lang.String _callService_arg3 = "";
        java.lang.String _callService__return = port.callService(usr, pwd, serviceID, applyData);
        System.out.println("callService.result=" + _callService__return);


        }
        // {
        // System.out.println("Invoking callServiceEx...");
        // java.lang.String _callServiceEx_arg0 = "";
        // java.lang.String _callServiceEx_arg1 = "";
        // java.lang.String _callServiceEx_arg2 = "";
        // java.lang.String _callServiceEx_arg3 = "";
        // java.lang.String _callServiceEx_arg4 = "";
        // java.lang.String _callServiceEx_arg5 = "";
        // java.lang.String _callServiceEx__return = port.callServiceEx(_callServiceEx_arg0, _callServiceEx_arg1, _callServiceEx_arg2, _callServiceEx_arg3, _callServiceEx_arg4, _callServiceEx_arg5);
        // System.out.println("callServiceEx.result=" + _callServiceEx__return);


        // }
        // {
        // System.out.println("Invoking mdmSubscribe...");
        // java.lang.String _mdmSubscribe_arg0 = "";
        // java.lang.String _mdmSubscribe__return = port.mdmSubscribe(_mdmSubscribe_arg0);
        // System.out.println("mdmSubscribe.result=" + _mdmSubscribe__return);


        // }

        System.exit(0);
    }

}
